fix(cdk): bump tsx 4.6.0 → 4.19.2
I got the following weird error when I ran
`pnpm tsx ./scripts/set-rp-origin`:

    node:internal/process/esm_loader:40
          internalBinding('errors').triggerUncaughtException(
                                ^
    Error: tsx must be loaded with --import instead of --loader
The --loader flag was deprecated in Node v20.6.0
        at Q (file:///node_modules/.pnpm/tsx@4.6.0/node_modules/tsx/dist/esm/index.mjs:1:1793)
        at Hooks.addCustomLoader (node:internal/modules/esm/hooks:202:24)
        at Hooks.register (node:internal/modules/esm/hooks:168:16)
        at async initializeHooks (node:internal/modules/esm/utils:233:5)
        at async customizedModuleWorker (node:internal/modules/esm/worker:104:24)

    Node.js v18.20.4

Upgrading `tsx` from 4.6.0 to 4.19.2 fixed the above error.